/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample.gradle.project;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testNothing() {
        assertTrue(true);
    }
}
